from typing import List, Optional, Any, Callable, Tuple, Dict

class PyConfig:
    def __init__(
        self,
        max_allowed_loops: int = 10,
        sleep_interval: int = 100,
        reconnect_time: int = 5,
        connection_initialization_timeout: float = 30.0,
        timeout: float = 10.0,
        urls: List[str] = [],
    ) -> None: ...

class RawValidator:
    @staticmethod
    def new() -> "RawValidator": ...
    @staticmethod
    def regex(pattern: str) -> "RawValidator": ...
    @staticmethod
    def contains(pattern: str) -> "RawValidator": ...
    @staticmethod
    def starts_with(pattern: str) -> "RawValidator": ...
    @staticmethod
    def ends_with(pattern: str) -> "RawValidator": ...
    @staticmethod
    def ne(validator: "RawValidator") -> "RawValidator": ...
    @staticmethod
    def all(validators: List["RawValidator"]) -> "RawValidator": ...
    @staticmethod
    def any(validators: List["RawValidator"]) -> "RawValidator": ...
    @staticmethod
    def custom(func: Callable[[str], bool]) -> "RawValidator": ...
    def check(self, msg: str) -> bool: ...

class StreamIterator:
    def __aiter__(self) -> "StreamIterator": ...
    def __anext__(self) -> str: ...
    def __iter__(self) -> "StreamIterator": ...
    def __next__(self) -> str: ...

class RawStreamIterator:
    def __aiter__(self) -> "RawStreamIterator": ...
    def __anext__(self) -> str: ...
    def __iter__(self) -> "RawStreamIterator": ...
    def __next__(self) -> str: ...

class RawHandler:
    def id(self) -> str: ...
    async def send_text(self, text: str) -> None: ...
    async def send_binary(self, data: bytes) -> None: ...
    async def send_and_wait(self, message: str) -> str: ...
    async def wait_next(self) -> str: ...
    async def subscribe(self) -> RawStreamIterator: ...

class RawHandle:
    async def create(self, validator: RawValidator, keep_alive_message: Optional[str]) -> RawHandler: ...
    async def remove(self, id: str) -> bool: ...

class RawPocketOption:
    def __init__(self, ssid: str) -> None: ...
    @staticmethod
    async def create(ssid: str) -> "RawPocketOption": ...
    @staticmethod
    def new_with_url(ssid: str, url: str) -> "RawPocketOption": ...
    @staticmethod
    async def create_with_url(ssid: str, url: str) -> "RawPocketOption": ...
    @staticmethod
    def new_with_config(ssid: str, config: PyConfig) -> "RawPocketOption": ...
    @staticmethod
    async def create_with_config(ssid: str, config: PyConfig) -> "RawPocketOption": ...
    async def wait_for_assets(self, timeout_secs: float) -> None: ...
    def is_demo(self) -> bool: ...
    async def buy(self, asset: str, amount: float, time: int) -> Tuple[str, Dict[str, Any]]: ...
    async def sell(self, asset: str, amount: float, time: int) -> Tuple[str, Dict[str, Any]]: ...
    async def check_win(self, trade_id: str) -> Dict[str, Any]: ...
    async def get_deal_end_time(self, trade_id: str) -> Optional[int]: ...
    async def candles(self, asset: str, period: int) -> List[Dict[str, Any]]: ...
    async def get_candles(self, asset: str, period: int, offset: int) -> List[Dict[str, Any]]: ...
    async def get_candles_advanced(self, asset: str, period: int, offset: int, time: int) -> List[Dict[str, Any]]: ...
    async def balance(self) -> float: ...
    async def closed_deals(self) -> List[Dict[str, Any]]: ...
    async def clear_closed_deals(self) -> None: ...
    async def opened_deals(self) -> List[Dict[str, Any]]: ...
    async def payout(self) -> Dict[str, int]: ...
    async def history(self, asset: str, period: int) -> List[Dict[str, Any]]: ...
    async def subscribe_symbol(self, symbol: str) -> StreamIterator: ...
    async def subscribe_symbol_chuncked(self, symbol: str, chunck_size: int) -> StreamIterator: ...
    async def subscribe_symbol_timed(self, symbol: str, time: Any) -> StreamIterator: ...
    async def subscribe_symbol_time_aligned(self, symbol: str, time: Any) -> StreamIterator: ...
    async def send_raw_message(self, message: str) -> None: ...
    async def create_raw_order(self, message: str, validator: RawValidator) -> str: ...
    async def create_raw_order_with_timeout(self, message: str, validator: RawValidator, timeout: Any) -> str: ...
    async def create_raw_iterator(
        self, message: str, validator: RawValidator, timeout: Optional[Any]
    ) -> RawStreamIterator: ...
    async def get_server_time(self) -> int: ...
    async def disconnect(self) -> None: ...
    async def connect(self) -> None: ...
    async def reconnect(self) -> None: ...
    async def unsubscribe(self, asset: str) -> None: ...
    async def create_raw_handler(self, validator: RawValidator, keep_alive: Optional[str]) -> RawHandler: ...

class Logger:
    def __init__(self) -> None: ...
    def debug(self, message: str) -> None: ...
    def info(self, message: str) -> None: ...
    def warn(self, message: str) -> None: ...
    def error(self, message: str) -> None: ...

class LogBuilder:
    def __init__(self) -> None: ...
    def create_logs_iterator(self, level: str, timeout: Optional[Any]) -> Any: ...
    def log_file(self, path: str, level: str) -> None: ...
    def terminal(self, level: str) -> None: ...
    def build(self) -> None: ...

class StreamLogsLayer: ...
class StreamLogsIterator: ...

class PyContext:
    @property
    def market(self) -> "PyVirtualMarket": ...
    def get_time(self) -> int: ...

class PyVirtualMarket:
    def balance(self) -> float: ...
    def buy(self, asset: str, amount: float, time: int) -> Tuple[str, Any]: ...
    def sell(self, asset: str, amount: float, time: int) -> Tuple[str, Any]: ...
    def check_win(self, id: str) -> Any: ...

class PyStrategy:
    def on_start(self, ctx: PyContext) -> None: ...
    def on_candle(self, ctx: PyContext, asset: str, candle: str) -> None: ...
    def on_stop(self) -> None: ...

class PyBot:
    def __init__(self, client: RawPocketOption, strategy: PyStrategy) -> None: ...
    def add_asset(self, asset: str, timeframe: int) -> None: ...
    async def run(self) -> None: ...

def start_tracing(level: str = "info") -> None: ...
