stages:
  - docs
  - deploy

pages:
  stage: docs
  image: node:20-bookworm
  tags:
    - linux
  before_script:
    - npm ci
  script:
    - npm run build
  artifacts:
    paths:
      - public
    expire_in: 7 days
  only:
    - main
    - master
  dependencies: []

deploy:
  stage: deploy
  image: node:20-bookworm
  tags:
    - linux
  script:
    - echo "Deploy to GitLab Pages/"
  environment:
    name: production
    url: https://chipatrade.gitlab.io/chipadevorg/BinaryOptionsTools-v2/
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
  dependencies:
    - pages
