[workspace]
resolver = "2"

exclude = [
    "BinaryOptionsToolsJs",
    "BinaryOptionsToolsV2"
]

members = [
    "crates/binary_options_tools",
    "crates/core", "crates/core-pre",
    "crates/macros",
]

