/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "BinaryOptionsTools V2",
  "tagline": "The most advanced binary options trading library for Python, JavaScript, and Rust.",
  "favicon": "img/favicon.svg",
  "url": "https://chipadevteam.github.io",
  "baseUrl": "/BinaryOptionsTools-v2/",
  "organizationName": "chipadevteam",
  "projectName": "BinaryOptionsTools-v2",
  "onBrokenLinks": "warn",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "./sidebars.js",
          "path": "../docs",
          "routeBasePath": "/",
          "editUrl": "https://gitlab.chipatrade.com/chipadevorg/BinaryOptionsTools-v2/-/tree/master/docs/"
        },
        "blog": false,
        "theme": {
          "customCss": "./src/css/custom.css"
        }
      }
    ]
  ],
  "themeConfig": {
    "image": "img/binary-options-social-card.jpg",
    "announcementBar": {
      "id": "chipa_ecosystem_2026_01",
      "content": "✨ <b><a target=\"_blank\" rel=\"noopener\" href=\"https://chipaeditor.com/?utm_source=docs&utm_medium=announcement&utm_campaign=BinaryOptionsToolsV2\">ChipaEditor</a></b> — build, backtest &amp; deploy AI-assisted trading strategies in CHTL, free. &nbsp;|&nbsp; 📈 Trade crypto perps &amp; spot on <b><a target=\"_blank\" rel=\"noopener\" href=\"https://exchange.chipatrade.com/trade/BTC?ref=Z1RN8GBS\">ChipaX</a></b>.",
      "backgroundColor": "#22d3ee",
      "textColor": "#06202a",
      "isCloseable": true
    },
    "navbar": {
      "title": "BinaryOptionsTools V2",
      "logo": {
        "alt": "BinaryOptionsTools Logo",
        "src": "img/logo.svg"
      },
      "items": [
        {
          "type": "docSidebar",
          "sidebarId": "tutorialSidebar",
          "position": "left",
          "label": "Documentation"
        },
        {
          "to": "/api/reference",
          "label": "API Reference",
          "position": "left"
        },
        {
          "to": "/examples",
          "label": "Examples",
          "position": "left"
        },
        {
          "to": "/ecosystem",
          "label": "Chipa Ecosystem",
          "position": "left"
        },
        {
          "href": "https://chipaeditor.com/?utm_source=docs&utm_medium=navbar&utm_campaign=BinaryOptionsToolsV2",
          "label": "✨ ChipaEditor",
          "position": "right",
          "className": "navbar-cta-editor"
        },
        {
          "href": "https://exchange.chipatrade.com/trade/BTC?ref=Z1RN8GBS",
          "label": "📈 Trade on ChipaX",
          "position": "right",
          "className": "navbar-cta-exchange"
        },
        {
          "href": "https://gitlab.chipatrade.com/chipadevorg/BinaryOptionsTools-v2",
          "label": "GitLab",
          "position": "right"
        },
        {
          "href": "https://discord.gg/p7YyFqSmAz",
          "label": "Discord",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Documentation",
          "items": [
            {
              "label": "Getting Started",
              "to": "/"
            },
            {
              "label": "API Reference",
              "to": "/api/reference"
            },
            {
              "label": "Examples",
              "to": "/examples"
            }
          ]
        },
        {
          "title": "Community",
          "items": [
            {
              "label": "Discord",
              "href": "https://discord.gg/p7YyFqSmAz"
            },
            {
              "label": "GitLab Issues",
              "href": "https://gitlab.chipatrade.com/chipadevorg/BinaryOptionsTools-v2/-/issues"
            }
          ]
        },
        {
          "title": "Chipa Ecosystem",
          "items": [
            {
              "label": "ChipaEditor — AI Strategy Builder",
              "href": "https://chipaeditor.com/?utm_source=docs&utm_medium=footer&utm_campaign=BinaryOptionsToolsV2"
            },
            {
              "label": "ChipaX — Crypto Exchange",
              "href": "https://exchange.chipatrade.com/trade/BTC?ref=Z1RN8GBS"
            },
            {
              "label": "Ecosystem Overview",
              "to": "/ecosystem"
            },
            {
              "label": "ChipaTrade",
              "href": "https://chipatrade.com"
            }
          ]
        },
        {
          "title": "More",
          "items": [
            {
              "label": "GitLab",
              "href": "https://gitlab.chipatrade.com/chipadevorg/BinaryOptionsTools-v2"
            },
            {
              "label": "PyPI",
              "href": "https://pypi.org/project/BinaryOptionsToolsV2/"
            },
            {
              "label": "crates.io",
              "href": "https://crates.io/crates/binary_options_tools"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2026 ChipaDevTeam. Build strategies with <a href=\"https://chipaeditor.com/?utm_source=docs&utm_medium=footer&utm_campaign=BinaryOptionsToolsV2&utm_content=copyright\">ChipaEditor</a> · Trade on <a href=\"https://exchange.chipatrade.com/trade/BTC?ref=Z1RN8GBS\">ChipaX</a>. Built with Docusaurus."
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [
        "python",
        "rust",
        "kotlin",
        "swift",
        "go",
        "ruby",
        "csharp",
        "javascript",
        "typescript"
      ],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "colorMode": {
      "defaultMode": "dark",
      "disableSwitch": false,
      "respectPrefersColorScheme": true
    },
    "algolia": {
      "appId": "YOUR_APP_ID",
      "apiKey": "YOUR_API_KEY",
      "indexName": "binaryoptionstools",
      "contextualSearch": true,
      "externalUrlRegex": "external\\.com",
      "searchParameters": {},
      "searchPagePath": "search"
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "storage": {
    "type": "localStorage",
    "namespace": false
  },
  "future": {
    "v4": {
      "removeLegacyPostBuildHeadAttribute": false,
      "useCssCascadeLayers": false,
      "siteStorageNamespacing": false,
      "fasterByDefault": false,
      "mdx1CompatDisabledByDefault": false
    },
    "faster": {
      "swcJsLoader": false,
      "swcJsMinimizer": false,
      "swcHtmlMinimizer": false,
      "lightningCssMinimizer": false,
      "mdxCrossCompilerCache": false,
      "rspackBundler": false,
      "rspackPersistentCache": false,
      "ssgWorkerThreads": false,
      "gitEagerVcs": false
    },
    "experimental_vcs": {},
    "experimental_router": "browser"
  },
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "plugins": [],
  "themes": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "format": "mdx",
    "mermaid": false,
    "emoji": true,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    },
    "hooks": {
      "onBrokenMarkdownLinks": "warn",
      "onBrokenMarkdownImages": "throw"
    }
  }
};
