[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "binary-options-tools-uni"
version = "0.1.0"
description = "Python bindings for the Binary Options Tools (Rust), packaged with a platform DLL."
license = { text = "MIT" }
dependencies = []

[tool.setuptools]
package-dir = { "" = "." }

[tool.setuptools.packages.find]
where = [""]
include = ["binary_options_tools_uni*"]

[tool.setuptools.package-data]
"binary_options_tools_uni" = ["*.dll", "*.so", "*.dylib"]
